### ISSUE TITLE
Extend clamping to initial value functionality

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#104]
Following on from a question in #96, add a test (and implementation) for `clamp prefix:name` where the variable `prefix:name` is defined by an equation that refers to other variables.

It looks like creating a Python version of https://chaste.cs.ox.ac.uk/trac/browser/chaste/projects/FunctionalCuration/test/TestOptionalVariables.hpp#L100 should test this.

**Comment by MichaelClerx** [comment]
Done in #158
