### ISSUE TITLE
Consistency checks for model interface

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#105]
Have some sanity checks before/after modification that report errors helpfully for the user.

- [x] ~Double~ Inconsistent inputs
- [x] ~Double~ Inconsistent outputs
- [x] Input/output overlap: must have same units
- [x] Check that a variable isn't defined more than once in the interface. Have a check before making changes that we don't have 2 define and/or clamp clauses targeting the same variable, and produce a friendly error.

**Comment by MichaelClerx** [comment]
I guess #130 is another one

**Comment by MichaelClerx** [comment]
I think we've more or less got this in #158 ?
