### ISSUE TITLE
Support the original_definition construct

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#108]
See https://chaste.cs.ox.ac.uk/trac/browser/chaste/projects/FunctionalCuration/test/TestAdvancedModelInterface.hpp for the C++ test of this.

Part of #23. ~Blocked by #97.~

**Comment by MichaelClerx** [comment]
"Original definition" suggests that this refers to the model equation, so all _before_ model modification and unit conversion. Is that right?

**Comment by MichaelClerx** [comment]
(And should `units_of` be read as `original_units_of` ?)

**Comment by jonc125** [comment]
Yes, original definition is before modifications.

--
Written on a smartphone; please excuse brevity!
________________________________

**Comment by MichaelClerx** [comment]
Thinking about how to implement this...

- You might have an equation like "x = y + original_definition", where "y" will need to be created. So doing the full equation _before_ modification won't be possible
- So we'll need to gather the original definitions before doing any modifications, create sympy equations and store these. So a scan over equations to search for RHS's, and make "original" definition objects store the appropriate sympy to insert when their to_sympy is later called

**Comment by jonc125** [comment]
When parsing the protocol, I'd store `original_definition` as a special symbol/token within the equation. Then when modifying the model, you can `xreplace` that symbol by the RHS from the original defining equation within the model. Sympy always copies rather the modifying in-place, so that won't cause any nasty side effects.

**Comment by MichaelClerx** [comment]
See https://github.com/ModellingWebLab/cellmlmanip/issues/273#issuecomment-620058512

**Comment by MichaelClerx** [comment]
> Yes, original definition is before modifications.

So if we have

```
a = 10 mV
b = 20 mV
c = a + b
```

and then I convert `a` to `V`, `b` to `4 * a`, and then set `c = 1 mV + original_definition`. Does that mean `c  = 31mV` ? Or `c = 51mV` ?

**Comment by MichaelClerx** [comment]
I'm guessing a use case could easily redefine a and b, and then say "c is still a + b, only with an extra factor 2" or something. Then you'd definitely mean "updated a and b"

**Comment by jonc125** [comment]
The 'if we have' bit is what the model says?

Then the original_definition would refer to the model's `a` and `b` `VariableDummy` objects, pre-units-conversion. So `c` would evaluate to `51mV`.

**Comment by MichaelClerx** [comment]
Right, but it would refer to the updated ones? So if it used to be "a + b", it won't now be "a-before-i-changed-it + b-before-i-changed-it" ?

**Comment by jonc125** [comment]
No, it should be the original ones. Since unit conversion creates new variables, it doesn't remove the old ones. It moves annotations over (by moving the cmeta:id) but doesn't change the variable names.

**Comment by MichaelClerx** [comment]
OK so it'd evaluate to 31mV then?

**Comment by jonc125** [comment]
Ah, yes, sorry, mis-read the numbers!

**Comment by MichaelClerx** [comment]
I'm still not entirely sure I know what we want :D

Simpler example:

1. I have "c = a + b"
2. The original RHSs are `a = a1` and `b = b1`
3. I update `a = a2` and `b = b2`, then set `c = original_definition`
4. Does that mean `c = a1 + b1`? or `c = a + b = a2 + b2`?

**Comment by MichaelClerx** [comment]
Not asking what cellmlmanip would do or anything like that, just what we want the result to be :-)

**Comment by MichaelClerx** [comment]
Harder version:

1. I have `c = a + b`
2. The original RHSs are `a = a1(x)` and `b = b1(x)`
3. I update `a = a2(x*)` and `b = b2(x*)`, then set `c = original_definition`
4. Does that mean `c = a1(x) + b1(x)`? or `c = a + b = a2(x*) + b2(x*)`?

where x is the rest of the model without modifications, and x* is the rest of the model with modifications

**Comment by jonc125** [comment]
If by 'update' you mean using `define` then I think `c = a2 + b2`. Because you haven't changed what `a` and `b` are, just their defining equations.

If by update you mean requesting `a` and `b` in different units using `input` or `output` then `c = a1 + b1` (or rather, it evaluates to the same result). Because the `a` and `b` referenced in the protocol are now different variables from the `a` and `b` in the model and hence in the original RHS.

**Comment by MichaelClerx** [comment]
> Because the a and b referenced in the protocol are now different variables from the a and b in the model and hence in the original RHS.

But surely that's an implementation detail? Not something the user would expect?

**Comment by jonc125** [comment]
I think we should define `original_definition` as a purely local construct. It doesn't give you all the original model wherever it references variables, it only gives you what the RHS of that equation was before the `define` got to it.

The unit conversion stuff is defined as just affecting the model-protocol interface, not what the internal model equations do, so I think it's reasonable to expect that you'd still have the internal model variables referenced on the RHS. But if you've used `define` to change the *definition* of those equations, then you'd expect the simulation result to change.

**Comment by MichaelClerx** [comment]
OK, so we'd have to do something like this:

- before unit conversion, run over all RHSs in defines/clamp-tos (but not optionals default expressions), check if they have an `original_definition` in there somewhere.
  - There doesn't seem to be a traverse method? So `get_children_expr` would have to be used?
  - There's no token for `original_definition`, it just gets passed to the `variable_generator`
- This is all necessarily pre-sympy conversion, because that requires all variables to be resolvable, and the equations can contain variables that don't exist yet. E.g. you could have `x = new_variable + original_definition`, so converting the entire RHS of `x` isn't possible until later, during the modification/creation loop
  - but the original_definition can be fully resolved (unless the model has issues), so we should be able to create a new model variable called e.g. `original_definition_of_x` at this point, and set its definition to be the same as `x`
  - create a map `original_definitions[var_using_org_def_in_its_new_rhs] = new_var_with_copy_of_the_old_rhs
- tell variable_generator to resolve `original_definition` to the correct original variable.
  - we can look this up in the map, but we need to know the LHS the equation was for
  - so maybe store this in the Name token?

**Comment by jonc125** [comment]
I was thinking you could change the variable generator so if it saw `original_definition` as a name it gave you a special `Dummy` subclass or similar. That'd be easy to pick up using `.atoms` when processing each equation and you could create the `original_definition_of_x` variable at that point?

**Comment by MichaelClerx** [comment]
One downside would be that it'd then fail silently anywhere if you used the `original_definition` somewhere it's not allowed to go

**Comment by jonc125** [comment]
You can put an error check in for that though?

**Comment by MichaelClerx** [comment]
Yeah, you just have to remember each time you use it, that's all

**Comment by jonc125** [comment]
If we did forget somewhere we'd get a more obscure undefined variable or assertion tripped later on I think.

**Comment by MichaelClerx** [comment]
It _will_ refer to the unit-converted version I think, if we do that (because we don't do the sympy conversion until after unit conversion)

**Comment by jonc125** [comment]
Ah, that's a pain! Hmm...

**Comment by MichaelClerx** [comment]
Not saying it doesn't _work_...

**Comment by jonc125** [comment]
You can traverse the action expression tree using `.tokens` on everything to get children, and checking for `instance(node, Variable)` to spot variable references, then comparing `.name() == 'original_definition'`.

**Comment by jonc125** [comment]
And once you've spotted that `original_definition` exists on a RHS, it's fine (pre-units-conversion) to call `eq.var.to_sympy` because the LHS must exist in the model for an original definition to be present, then call `model.get_definition` and save the RHS of that for later use.

**Comment by jonc125** [comment]
Would that work?

**Comment by MichaelClerx** [comment]
Yeah I think so

**Comment by MichaelClerx** [comment]
I could even save all the original equations of variables that will be redefined. Doesn't cost much - might even be cheaper than traversing the RHS

**Comment by jonc125** [comment]
That's a sneaky idea :)

**Comment by MichaelClerx** [comment]
Closed in #175
