### ISSUE TITLE
Can we install without cython already being present?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#11]
See e.g. https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords `setup_requires` keyword

**Comment by jonc125** [comment]
`setup_requires` doesn't really help, as you need to have run the `setup.py` to find out it's there, by which point you need to have imported the things listed... bit chicken & egg.

It is I believe possible to distribute the Cython-generated C code, but probably creating binary wheels for different target systems is a better approach.

**Comment by MichaelClerx** [comment]
Will we not be compiling new code for new models?

**Comment by MichaelClerx** [comment]
> setup_requires doesn't really help, as you need to have run the setup.py to find out it's there, by which point you need to have imported the things listed... bit chicken & egg.

I was wondering about that! A potential work-around would be to have imports inside methods, but then you'd have to pass in methods rather than executing them when creating the setup.py arguments... So not sure how/if they solve this

**Comment by jonc125** [comment]
Yes, you'd still need Cython at run-time.

I read somewhere, can't remember where now, that `setup_requires` was not really fixable and people were looking at solutions outside `setup.py`.
