### ISSUE TITLE
Make tests run faster

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#112]
- [x] Run profiling to see where most time is spent
- [ ] Presumably, fix #41

Current tests take 10-15 minutes and use excessive computing power

**Comment by MichaelClerx** [comment]
Added [pytest-profiling](https://pypi.org/project/pytest-profiling/) plugin (see contributing.md).

Not sure how good it is, doesn't seem to filter out all of pytest's calls

**Comment by MichaelClerx** [comment]
Example SVG file generated for `test_algebraic_models.py`

[combined.zip](https://github.com/ModellingWebLab/weblab-fc/files/4250729/combined.zip)

Seems to indicate that all time is spent parsing, rather than manipulating or running experiments @jonc125 ?

**Comment by jonc125** [comment]
That would make sense; the protocols themselves are tiny so running will be small. Parsing the model is ~3%, compiling Cython code ~7.5%, modifying ~2%. pyparsing 77% and converting the parse actions via expr() 10%.

**Comment by MichaelClerx** [comment]
On my laptop, the time taken for `test_algebraic_models` (without profiling enabled) is `87.8s`, so that means `68` seconds spent in `pyparsing`

**Comment by MichaelClerx** [comment]
So 34 seconds per protocol. Persumably this is just time spent parsing the library files? It can't take 34 seconds to parse those protocol files themselves, can it?

**Comment by jonc125** [comment]
If they're now fast enough to be live-able with, then yes. @skeating ?
