### ISSUE TITLE
Change the file name of protocol.py

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/weblab-fc#120]
For some hard to fathom reason PyCharm debugging actually excludes files named 'protocol.py'. This can be fixed in some cases by editing the pycharm files but not when its installed on an ubuntu VM. 

To avoid anyone else encountering this we should probably change the name of our file.

**Comment by MichaelClerx** [comment]
https://blog.jetbrains.com/pycharm/2020/03/pycharm-2020-1-eap-6/
