### ISSUE TITLE
Optimise parsing of BasicLibrary protocol

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/weblab-fc#123]
When parsing the nested protocol each protocol parses BasicLibrary.txt. It might make sense to cache this somewhere; particularly if fc might be called repeatedly with different protocols which might include this.

**Comment by jonc125** [comment]
See also #112 #41 #119.

**Comment by MichaelClerx** [comment]
Shall we close this now that it's cached? @skeating ?
