### ISSUE TITLE
Model interface: var specified as input & output must have same units

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#130]
Currently not checked

**Comment by MichaelClerx** [comment]
Added a test in https://github.com/ModellingWebLab/weblab-fc/pull/131/files

**Comment by jonc125** [comment]
At least, this is the case in pycml because the implementation there makes it fiendish to allow otherwise. I think for the sake of a user's sanity it's probably a reasonable restriction anyway, but happy to hear arguments the other way if you like!

**Comment by MichaelClerx** [comment]
My only objection is that the syntax makes it look like you can specify different units, whereas in fact it's 3 statements rolled into 2 constructs (x is in mV, x is an input, x is an output)

**Comment by jonc125** [comment]
Indeed. So, let's not implement a specific check for this yet and see whether our natural approach to unit conversions lets it work with different units. And if it does, we can say that's a feature not a bug :)

**Comment by MichaelClerx** [comment]
I'm not sure it follows unthinkingly...

    x = 1 mV
        oxmeta: membrane_voltage

add an output in V to get

    new_x = x * 1e-3
        oxmeta: membrane_voltage
    x = 1 mV

add an input in kV to get... an error? Can't assign a value to it now
Otherwise, would work out as

    new_new_x = x * 1e-3 * 1e-3
    new_x = new_new_x / 1e-3
    x = 1 mV

???

**Comment by MichaelClerx** [comment]
So we'd have to do inputs first, at least, I think

**Comment by jonc125** [comment]
Though we do do inputs first with the flow at present.

**Comment by MichaelClerx** [comment]
Yeah just saying we can't do it without thinking it through, which would have been nice :D

**Comment by MichaelClerx** [comment]
Input first case:

    x = 1 mV
        oxmeta: membrane_voltage

add an input in V to get

    new_x = 0.001 V
        oxmeta: membrane_voltage
    x = new_x * 1000 [mV/V]

add an output in kV to get

    new_new_x = new_x * 0.001 [kV/V]
        oxmeta: membrane_voltage
    new_x = 0.001 V
    x = new_x * 1000 [mV/V]

**Comment by jonc125** [comment]
Actually, I've just realised why there is a problem with this: you can't annotate both the input and the output variable with the ontology term if they're different variables!

**Comment by MichaelClerx** [comment]
Closed in #131
