### ISSUE TITLE
Make test_other_ontologies pass

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#141]
> test_other_ontologies has terms not in `oxmeta` and a generic vector output (not the state vector) - should be covered by #95 and #97 actually

Tried it, but doesn't work out of the box, so made this ticket for it

**Comment by jonc125** [comment]
`test_annotating_with_other_ontologies` in `test_various_protocols.py` would also come under this topic.

**Comment by MichaelClerx** [comment]
> `test_annotating_with_other_ontologies` in `test_various_protocols.py` would also come under this topic.

Same test, I think?

**Comment by MichaelClerx** [comment]
Might need splitting, that test, as it also tests annotating outputs with categories?

**Comment by MichaelClerx** [comment]
Or rename something like 'test_advanced_annotation' :D

**Comment by jonc125** [comment]
Fair enough :)

**Comment by MichaelClerx** [comment]
Closed in #174
