### ISSUE TITLE
Protocol.inputs?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#145]
The Protocol class has a property `inputs`, described as

```
        # A list of :class:`fc.language.statements.Assign` objects.
        # Each representing an assignment ``local var = expression``.
        self.inputs = []
```

so nothing to do with "inputs" in a model, defined within protocols? Should we call this something less confusing, e.g. `local_variables`?
Also mentioned in `Environment` class

**Comment by MichaelClerx** [comment]
Or `self.assignments` ?

**Comment by jonc125** [comment]
It's the external inputs to the protocol, arising from the `inputs` section in a protocol file. Perhaps the comment just needs updating to match that?
