### ISSUE TITLE
Piecewise?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#146]
There's currently an action called "Piecewise", but the code for parsing it looks like

```
    # If-then-else
    if_expr = p.Group(make_kw('if') - expr + make_kw('then') - expr +
                     make_kw('else') - expr).setName('IfThenElse').setParseAction(actions.Piecewise)
```
and similarly its action is
```
class Piecewise(BaseGroupAction):
    """Parse action for if-then-else."""

    def _expr(self):
        if_, then_, else_ = self.get_children_expr()
        return E.If(if_, then_, else_)
```

does this mean there's no support for a `MathML:Piecewise` ?

**Comment by jonc125** [comment]
I don't think `MathML:piecewise(args)` would work as expected, indeed. The reason if-then-else has Piecewise as an action is that it used to generate a MathML `<piecewise>` element when the parser had to convert to MathML for pycml.
