### ISSUE TITLE
Add tests for protocols with multiple time units specifications

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#151]
Add some tests for edge cases:

- Multiple `independent var units` declarations, with same units --> error?
- Multiple `independent var units` declarations, with different units --> error
- Time units set via `independent var units` and input/output, but OK --> not sure
- Time units set via `independent var units` and input/output, but conflicting --> error
- All of the above, but with part of the declarations in nested protocols

**Comment by jonc125** [comment]
> * Multiple `independent var units` declarations, with same units --> error?

Probably not, because that would most commonly arise in nested protocols.

> * Time units set via `independent var units` and input/output, but OK --> not sure

Think this is fine too. Redundant info, but that shouldn't prevent the protocol running.

> * All of the above, but with part of the declarations in nested protocols

The outcome should be the same. So can check just after interfaces are merged.

**Comment by MichaelClerx** [comment]
See also #136

**Comment by MichaelClerx** [comment]
Covered in #158
