### ISSUE TITLE
Consistent use of `get_variables_transitively` in model interface (actions.py)

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#152]
Should probably check for this at some point

**Comment by jonc125** [comment]
Did you spot something that might be wrong?

**Comment by MichaelClerx** [comment]
Just that we're using it in some places and not in others, and I've never used it, so maybe I should have?

**Comment by jonc125** [comment]
It's only needed to support vector outputs, so won't be needed everywhere. I think the only place this might affect is the sanity checking. At present it looks like this will ignore vector outputs, and that's probably OK.

**Comment by MichaelClerx** [comment]
Thanks!
