### ISSUE TITLE
Optional variables in model interface: add tests and support

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#157]
Required for #99

- Optional input: don't create if optional
- Optional output: not sure if we need to do much

`INa_IV_curves` contains examples of optional inputs, an optional output (with a default value), and an optional variable that isn't an input or output

**Comment by MichaelClerx** [comment]
Bit confused about the rules on https://chaste.cs.ox.ac.uk/trac/wiki/FunctionalCuration/ProtocolSyntax#Modelinterface

About inputs:

> If the variable doesn't exist, this is an error unless units are given - the variable is then created.

> Unless the variable is specified as optional (see below) it must also be given a value, either using an initial value here, or defining it by a define clause, or both (if defining by an ODE).

In the comments in the code for FC we seem to interpret this as "optional inputs do not need to be created", but the first sentence here contradicts that.

About outputs:

> Nothing is written about optional outputs!

About optional itself:

> If an optional variable doesn't appear in the model, then it is not an error for it to be referenced by an input, output, clamp or define construct. If a default clause is included, then it will be used as the variable's definition; otherwise any construct referencing the variable will simply be ignored.

This just seems to say "create any optional variable that has a default value", regardless of whether it's an input or output or neither?

**Comment by MichaelClerx** [comment]
But then it says

> Note that this 'optional-ness' only applies directly to uses within this section of the protocol - if a simulation or post-processing tries to access or set an optional variable that doesn't exist, this is still an error. The exceptions are post-processing assignments and output specifications that are themselves guarded by an optional keyword. 

Which would make optional outputs pointless, because even though they get created, you're not allowed read them out later?

**Comment by MichaelClerx** [comment]
Protocols such as `INa_IV_curves` _do_ refer to optional outputs (with default values) in their post-processing though

**Comment by MichaelClerx** [comment]
Not sure how to create the optional variables now:

```
    var R units mJ_per_Mol_K = 8314.4621
    var F units C_per_Mol = 96485.3365
    optional oxmeta:temperature default 310 :: K
    optional oxmeta:sodium_reversal_potential default (R*oxmeta:temperature/F) * MathML:ln(oxmeta:extracellular_sodium_concentration / oxmeta:cytosolic_sodium_concentration)
    output oxmeta:sodium_reversal_potential units mV
```

To create a new variable for `oxmeta:temperature`, I need to know its units
The only way to get this seems to be to inspect the RHS.
However, the RHS is allowed to contain references to other optional variables, so I can't parse the RHS until I've created all optional variables

Secondly, because `oxmeta:temperature` isn't an input, if the user _does_ specify it then we don't know if we need to do any units conversion on this value. The suggested way to work this out is to look at equations that use it and then make both sides match (see #144). In other words, if the user specifies an `oxmeta:temperature` variable then its units in the expression for `optional oxmeta:sodium_reversal_potential` will depend on what the units of the LHS are. But we don't know what they are, because it's optional, and not an input, so we need to guess the units by looking at the RHS?

**Comment by jonc125** [comment]
I'm going to try to respond to points in one go rather than individual questions above. Shout if I miss anything!

* The basic rule for whether to create an optional variable is to do so only if you have sufficient information. Which means you need both units and value (defining equation). This info may come from different sources however.
    * The value could come from an `input` clause, a `define` clause, or a `default` clause within the `optional` statement. (Or a combination iff a state variable.)
    * Units could be specified in an `input` or `output` clause, or derived from the defining equation's RHS. The former takes precedence over the latter if both exist.
* If you don't have sufficient info then the optional variable isn't created. If it's an output, then it won't exist for reading by post-processing etc. This will cause an error. *But* the post-processing statement itself can be marked as optional, in which case this error is swallowed and that statement ignored. Similarly for protocol outputs etc. That part is all implemented already.
* Defining optional variables with their default clause is indeed difficult. Especially because the default clause might reference other optional variables, etc. Pycml used 'magic' units and resolved these once all modifications were done. We might be better doing the following:
    * If an optional variable doesn't exist in the model, add to the `define` equations an assignment using its default clause as RHS.
    * Do a topological sort of the `define` equations so we know all variables appearing in the RHS of an assignment when we get to it.
    * #159 will probably need to change slightly, as currently it converts `define` equations assuming the units of the LHS are known. In the case where they aren't, it'll need to convert the RHS in isolation, then use those units for the RHS. Which would benefit from an extra public method in the `UnitCalculator` class to do this.

**Comment by jonc125** [comment]
This extra method in `UnitConverter` should handle the last point:
```python
    def set_lhs_units_from_rhs(self, equation):
        """Set the units of the variable assigned to based on the expression assigned.

        :param equation: a :class:`sympy.Eq` instance with a :class:`VariableDummy` on the left hand side
        :returns: a new version of the equation, but with the RHS using consistent units throughout (with
            conversions if needed) and the ``units`` attribute on the LHS updated to match
        """
        lhs = equation.lhs
        assert isinstance(lhs, model.VariableDummy)
        new_rhs, was_converted, rhs_units = self._convert_expr_recursively(equation.rhs, None)
        lhs.units = rhs_units
        if was_converted:
            equation = sympy.Eq(lhs, new_rhs)
        return equation
```

**Comment by MichaelClerx** [comment]
Can we not come up with something simpler / a more explicit syntax so that the user has a better chance of understanding what's going on?

**Comment by MichaelClerx** [comment]
I don't see why the WL1 behaviour or FC language should be set in stone?

**Comment by jonc125** [comment]
I don't mind adding new features. But I'd rather not break anything in WL1 in our first iteration of the new backend! Otherwise it'll be harder to track down any bugs that do arise.

**Comment by jonc125** [comment]
To expand on that point: I think the *intended semantics* of `optional` as currently implemented are useful: I don't want to lose them. We could certainly clarify the documentation. And we could add new syntax to make it clearer how it works (deprecating the old version). Along with the whole units specification question. So maybe something like
```
variable <prefix:name> [units <uname>] [input] [output] [initial value <val>] [optional [default <simple_expr>]]
```
that combines our existing `input`, `output` and `optional` clauses. It could even deprecate `var` for cases that are neither input nor output!

I think it is useful to have the system figure out the units sometimes without having to specify them: occasionally you do want a variable in units consistent with whatever the model currently uses.

**Comment by MichaelClerx** [comment]
I like that proposal
