### ISSUE TITLE
Add code coverage to CI

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#176]

**Comment by MichaelClerx** [comment]
Looks like the travis config is OK already. But doesn't show up in "Integrations", so maybe we need to do something on codecov @jonc125 ? Guess it'd be from your account?

**Comment by jonc125** [comment]
It shows up on https://codecov.io/gh/ModellingWebLab/weblab-fc but wasn't at https://github.com/organizations/ModellingWebLab/settings/installations/170703. Should now be linked fully.
