### ISSUE TITLE
Re-enable or get rid of long tests

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#181]
Currently no strategy for running tests marked with

```
#@pytest.mark.skipif(os.getenv('FC_LONG_TESTS', '0') == '0', reason="FC_LONG_TESTS not set to 1")
```

Namely:
- [x] test_ical_proto.py::test_ical --> Passes when run
- [x] test_s1s2_protocol.py::test_s1_s2
- [x] test_python_reproducibility.py --> Separate issue #24

**Comment by MichaelClerx** [comment]
The first two work, the third is a separate issue.

@jonc125 Do we keep these tests and set up an cron job or delete them?

**Comment by jonc125** [comment]
Set up a cron job for them I think. We'll need it for #161 certainly.

**Comment by jonc125** [comment]
Closing this as it's covered in #24.
