### ISSUE TITLE
Trac: Allow non-oxmeta annotations for variables

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#199]
https://chaste.cs.ox.ac.uk/trac/ticket/1903

> Child of https://chaste.cs.ox.ac.uk/trac/ticket/1873. Additional related tasks in https://chaste.cs.ox.ac.uk/trac/ticket/2529.

**Comment by MichaelClerx** [comment]
See https://github.com/ModellingWebLab/weblab-fc/issues/141

**Comment by jonc125** [comment]
The remaining tasks here are just a duplicate of #169.
