### ISSUE TITLE
Split CompactSyntaxParser into multiple files

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#26]
For example, actions can easily go into one or multiple files + get some more documentation

Not sure we still need to be able to run it as a script either...

**Comment by jonc125** [comment]
Indeed, the script running was just for the C++ implementation so can go.

All the XML generation could be stripped out too.

It was in one file originally in order to support running as a script to generate XML without having to muck around with the path too much.

**Comment by MichaelClerx** [comment]
Are we OK with dropping export of protocol files then? So we read but never write it?

**Comment by jonc125** [comment]
That's correct. The XML export was only so pycml could read it back in!

**Comment by MichaelClerx** [comment]
With xml support and script bits gone, it's become a lot more managable, so closing this now

**Comment by MichaelClerx** [comment]
Re-opening!
Things like `fc.parsing.CompactSyntaxParser.Actions.Protocol` can probably be somewhere much simpler, e.g. `fc.parsing.actions.Protocol` or even `fc.parsing.Protocol`

**Comment by jonc125** [comment]
Is there a benefit to them having shorter 'paths'? Not that I'm averse to splitting it up, just anxious to keep focused on end goals!

**Comment by MichaelClerx** [comment]
Main benefit would be easier to find code and easier to navigate files

**Comment by jonc125** [comment]
Done in #84.
