### ISSUE TITLE
Migrate relevant issues from Chaste Trac

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#3]
List of open issues is at https://chaste.cs.ox.ac.uk/trac/query?status=assigned&status=new&status=reopened&group=status&milestone=Functional+curation

Also make new issues for relevant items in https://chaste.cs.ox.ac.uk/trac/ticket/2643

**Comment by MichaelClerx** [comment]
Ported them all. Will now check and close where needed
