### ISSUE TITLE
Can we start using f-strings?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#42]
https://realpython.com/python-f-strings/

Would be quite happy to. Is supported in Python 3.6 and upwards

**Comment by MichaelClerx** [comment]
For Cellmlmanip and weblab_cg we've decided 3.5 makes more sense. Wonder now if FC would ever be run on an old system...

**Comment by jonc125** [comment]
Depends. For the purposes of the grant we control what it runs on. But we should probably stick to the same minimum Python version for the whole ecosystem, for the sake of our own sanity if nothing else!

**Comment by MichaelClerx** [comment]
Ok! Closing in favour of #64

**Comment by MichaelClerx** [comment]
Re-opening now, since we're targeting 3.6!
(Probably 3.6+)
