### ISSUE TITLE
pip install fails due to `line-profiler`

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#43]
`pip install -e .[dev,test]`

Somewhere down the line, something pulls in `line-profiler`, which fails to install:

> Note: As of version 2.1.2, pip install line_profiler does not work. Please install as follows until it is fixed in the next release:

https://github.com/rkern/line_profiler

**Comment by MichaelClerx** [comment]
We _could_ fix this by adding it as a dependency ourselves, and pinning the version to an earlier one.
But don't really want to!

What do you think @jonc125 ?

**Comment by jonc125** [comment]
It's an optional dev dependency for us. So could just comment it out for now?
