### ISSUE TITLE
Faster stimulus implementation

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#47]
> Typically, the CellML version of a model includes a stimulus current.
This is essential a default protocol, and so it can be argued this should not be part of a model.

> - Note 1: The same holds for physical constants and physiological parameters such as temperature or membrane area: in a modular set-up these should really not be part of the _cell_ model.
> - Note 2: In addition, most stimulus protocols are discontinuous, and consist of a small jump of 0.5, 1, or 2ms in a 1000ms period.
Unless the solver somehow knows when these jumps are, simulations need to be run with a maximum step size of e.g. 1ms.
This is inefficient during the systolic/refractory phase, where steps of over 100ms could otherwise be made.

Related to reset rules in CellML 2

**Comment by mirams** [comment]
Yes, WL and Chaste have always stripped out the stimulus for this reason.

But I forbid the use of reset rules for the stimulus!

There is no need to go and do the extra work of a root finding adventure for this, which is how reset rules are implemented in the solvers. We do already know where the jumps are from the metadata so we can just run solve in a couple of steps, stopping and starting where we already know (a-priori) that the stimulus applies.

**Comment by MichaelClerx** [comment]
Reset rules on the time variable won't be implemented with root finding. That would have to be handled differently

**Comment by MichaelClerx** [comment]
Anyway, I was only copying and pasting from earlier notes. CellML 2 won't be out before the end of the grant I'm sure :D

**Comment by MichaelClerx** [comment]
Closing in favour of the older ticket #193
