### ISSUE TITLE
Cut dependency on pycml

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#5]
At present running an experiment requires pycml to generate the manipulated model. This will change to use cellmlmanip & fccodegen.

- [x] As a first step, put a manually generated (using fccodegen) model in the tests and see if we can just simulate it.
- [x] Then call this automatically rather than calling pycml.
- [x] Then iteratively implement model manipulations. See #23.

**Comment by MichaelClerx** [comment]
I guess as far as this repo is concerned, the dependency has been cut @jonc125 ?

Just need to finish other tickets now, e.g. #23

**Comment by jonc125** [comment]
Yep!
