### ISSUE TITLE
Add protocol units to cellmlmanip unit registry

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/weblab-fc#65]
Using a model with units seconds (earm_noble_model_1990) and a protocol with units milliseconds causes a fail in unit conversion as the unit_registry does not know about ms. 

Initially incorrectly filed in https://github.com/ModellingWebLab/cellmlmanip/issues/110

This arises from https://github.com/ModellingWebLab/weblab-fc/issues/22

**Comment by MichaelClerx** [comment]
Should this be a separate unit registry to avoid clashes with units defined in CellML ?

**Comment by jonc125** [comment]
Yes, model and protocol should use separate registries.

**Comment by jonc125** [comment]
Obsoleted by latest cellmlmanip units work.
