### ISSUE TITLE
Change protocol parsing sequence & Protocol API?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#78]
At the moment, parsing a protocol seems to work as:

1. Create a `Protocol`, using a filename as a constructor argument
2. Call the parser from the protocol, returning a hierarchy of `CompactSyntaxParser.BaseAction` objects
3. Inside the protocol constructor, read out all the needed information from the hierarchy of baseactions and fill in the needed info in the protocol

I'm wondering if we wouldn't benefit more from something like:

1. Update the Protocol API so that you can create Protocol objects, without a file
2. Write a parse method that uses the CompactSyntaxParser to create and return a Protocol object (created via its API)

That gives you a cleaner separation, as the Protocol class doesn't need to know about parsing. Also a nice Protocol API could have e.g. objects for the various sections etc. it contains

**Comment by MichaelClerx** [comment]
More general question: do we want nice classes for everything, or lots of dicts and lists of tuples etc.

**Comment by MichaelClerx** [comment]
Some alternatives:

1. We write structured (but stupid) classes representing Protocols, all the sections, etc., and these are created by the parser
2. We update the BaseAction classes etc. to be these things

**Comment by jonc125** [comment]
We already have classes for some parts: simulations, language, etc. For things like the output specs, they're simple enough that a dict seems fine to me. Similarly the post-processing section is just a list of statements; the statements are 'clever' classes, but the list is just a list. So probably not worth changing how the non-model-interface parts are structured.

Cleaner separation sounds sensible though, in terms of moving more of the parsing out of the Protocol class, especially now we have **all** the model interface stuff here and not in pycml. And you'll need to create suitable structures for the interface stuff, which could perhaps live just on the parser side. The model compilation stuff (in `set_model`) could also be extracted.

However I'm not sure how much you can have a 'simple' protocol API and use parts separately as their own objects. Partly the considerations above. Partly that how a Protocol is structured is very tightly tied to how it is run, and the parts are quite intimately linked (e.g. through environment delegations). Very few of the member variables set up in `__init__` could be removed just to a parser; perhaps just `self.inputs`! Your protocol construction API would probably end up as just the equivalent of `proto.library.extend(...); proto.simulations.extend(...); ...`

**Comment by jonc125** [comment]
Consensus is to make the action classes more clever, so `_expr` just returns `self` for these, and they gain methods to do things like merge model interface sections when importing protocols. We'll make a start on this in #73.
