### ISSUE TITLE
When making a variable a state with a `define`, where does the initial value come from?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#81]
^ that

**Comment by jonc125** [comment]
`define` just adds/changes the defining equation, it doesn't affect other properties of the variable. So it'll keep any existing initial value, and you'll get an error if there isn't one. Typically it comes from the model, an `input <prefix:term> [units <uname>] [= <initial_value>]` line, or a `var <name> units <uname> [= <initial_value>]` line.

https://chaste.cs.ox.ac.uk/trac/wiki/FunctionalCuration/ProtocolSyntax#Modelinterface

**Comment by MichaelClerx** [comment]
So if I update the interface to create a new state, I have to give it an initial value somewhere else, e.g. in the tasks?

**Comment by jonc125** [comment]
No, elsewhere in the model interface section.

**Comment by MichaelClerx** [comment]
how?

**Comment by jonc125** [comment]
By also adding it as an input, or declaring it with `var`.

**Comment by jonc125** [comment]
e.g. `test/protocols/test_other_ontologies.txt`:
```
    input test:input units mV_per_ms = 0
    input test:V units mV = 0

    output test:V units mV
    output oxmeta:time units ms

    define diff(test:V; oxmeta:time) = test:input
```

**Comment by MichaelClerx** [comment]
Thanks
