### ISSUE TITLE
Attempting to create a protocol from non existent file

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/weblab-fc#82]
There are possibly two issues here:

1. If you call a Protocol with an non-existent file you do not get a nice exception. You get both FileNotFoundError and AttributeError from pyparsing as it throws one while dealing with other.
 So this test does not pass:
   def test_non_existent(self):
        proto_file = 'protocols/not_here.txt'
        self.assertRaises(FileNotFoundError, fc.Protocol(proto_file))

Are  we worried ??

2.  If the protocol tries to import from the library files and for some reason doesnt find them then it just cleanly exits with no error at all. This one did worry me. Should we address this.

**Comment by jonc125** [comment]
I'd like nice exceptions from both of those!
