### ISSUE TITLE
Run test_sim_environments protocol

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#95]
Requires support for:
- [x] Model input that specifies initial_value for state variable (V)
- [x] Model input that doesn't exist in the model (SR_leak_current), creating the variable
- [x] ~Model input that specifies units, with conversion if necessary - only if we also test on a model that has SR_leak_current, need to check what would be suitable~
- [x] A `define` clause with a variable on the RHS - should be handled by existing code
- [x] A model parameter (SR_leak_current)
    * Need to think about how we want to handle setting the initial_value for this - possibly set the `VariableDummy` attribute? Because we'll never actually generate an equation setting it; it'll be read/written in the parameters vector.

**Comment by jonc125** [comment]
I've now sketched out how to tackle this, and some of #97 & #99, in https://github.com/ModellingWebLab/weblab-fc/compare/96-simple-clamping...95-sim-environments. Probably won't have time to get back to it until Thu/Fri, so feel free to pick up anyone if you get there before me!

**Comment by MichaelClerx** [comment]
@jonc125 re:

> only if we also test on a model that has SR_leak_current, need to check what would be suitable

did you mean test on a model that does _not_ have SR_leak_current? (In that case we get unit conversion from V to mV with paci. the SR leak is set to something not compatible with current so should always fail in a sensible model.)

**Comment by jonc125** [comment]
I don't think we need this with your new test cases.
