### ISSUE TITLE
Run test_clamping 1 & 2 protocols

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/weblab-fc#96]
Part of #23.

- [x] Should be just a matter of implementing the `ClampVariable` action to delegate to `ModelEquation`, providing syntactic sugar.

Tested in `test_algebraic_models.py`. Which means we also need:
- [x] Handle models with no free variable in code generation.

- [x] The `var = var` equation that clamping to initial value results in gets simplified to just `BooleanTrue` by sympy. We might need to represent this differently in sympy, and/or handle it specially in `_add_or_replace_equations`. I suspect the best option is only to treat clamping to fixed value as syntactic sugar, and keep a separate action for clamping to initial value. All such actions can then be processed separately just before or after `_add_or_replace_equations`.
    - Question: if the RHS of the existing equation defining `var` refers to other variables, should this be allowed?

Possible extension:
- [ ] Check that a variable isn't defined more than once in the interface. Have a check before making changes that we don't have 2 define and/or clamp clauses targeting the same variable, and produce a friendly error.

**Comment by MichaelClerx** [comment]
> Question: if the RHS of the existing equation defining var refers to other variables, should this be allowed?

I don't see why not! (from a user's point of view)

**Comment by jonc125** [comment]
I've created follow-on issues for the bits above not addressed in #98.
